const express = require('express')
const router = express.Router()
const movieRouter = require('../modules/movie/movie_routes')
const authRouter = require('../modules/auth/auth_routes')
const userRouter = require('../modules/users/users_routes')
const premiereRouter = require('../modules/premiere_location/premiere_routes')
const cinemaRouter = require('../modules/cinema/cinema_routes')
const scheduleRouter = require('../modules/schedule/schedule_routes')
const bookingRouter = require('../modules/booking/booking_routes')
const dashboardRouter = require('../modules/dashboard/dashboard_routes')

router.use('/movie', movieRouter)
router.use('/auth', authRouter)
router.use('/users', userRouter)
router.use('/premiere-location', premiereRouter)
router.use('/cinema', cinemaRouter)
router.use('/schedule', scheduleRouter)
router.use('/booking', bookingRouter)
router.use('/dashboard', dashboardRouter)

module.exports = router
